# $Id: Makefile 573 2006-02-20 17:09:11Z stsp2 $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

EXTRA_AFLAGS := -ansi
EXTRA_CFLAGS := -Werror

lib-y   := bootstr.o devops.o init.o misc.o \
	   tree.o console.o printf.o p1275.o cif.o
