# $Id: Makefile 573 2006-02-20 17:09:11Z stsp2 $

prism54-objs := islpci_eth.o islpci_mgt.o \
                isl_38xx.o isl_ioctl.o islpci_dev.o \
		islpci_hotplug.o oid_mgt.o

obj-$(CONFIG_PRISM54) += prism54.o

